apiVersion: v1
kind: ConfigMap
metadata:
  name: vespa-app
  namespace: default
data:
  services.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <services version="1.0">
      <admin version="2.0">
        <adminserver hostalias="vespa-0"/>
      </admin>

      <container id="container" version="1.0">
        <search/>
        <document-api/>
        <http>
          <server id="default" port="8081"/>
        </http>
      </container>

      <content id="content" version="1.0">
        <redundancy>1</redundancy>
        <documents>
          <document type="animales" mode="index"/>
        </documents>
        <nodes>
          <node distribution-key="0" hostalias="vespa-0"/>
        </nodes>
      </content>
    </services>
  hosts.xml: |-
    <hosts>
      <host name="vespa-0.vespa.default.svc.cluster.local">
        <alias>vespa-0</alias>
      </host>
    </hosts>
  animales.sd: |-
    schema animales {
      document animales {
        field name type string { indexing: summary | attribute }
        field color type string { indexing: summary | attribute }
        field diet type string { indexing: summary | attribute }
        field family type string { indexing: summary | attribute }
        field habitat type string { indexing: summary | attribute }
        field predators type string { indexing: summary | attribute }
        field height_cm type float { indexing: summary | attribute }
        field weight_kg type float { indexing: summary | attribute }
        field lifespan_years type float { indexing: summary | attribute }
        field avg_speed_kmh type float { indexing: summary | attribute }
        field top_speed_kmh type float { indexing: summary | attribute }
        field countries_found type string { indexing: summary | attribute }
        field conservation_status type string { indexing: summary | attribute }
        field social_structure type string { indexing: summary | attribute }
        field gestation_days type float { indexing: summary | attribute }
        field offspring_per_birth type float { indexing: summary | attribute }
        field description type string { indexing: summary | index }
        field embedding type tensor<float>(x[384]) { 
          indexing: summary | attribute 
          attribute {
            distance-metric: euclidean
          }
        }
      }
      fieldset default { fields: name, description }
      rank-profile default {
        first-phase {
          expression: closeness(field, embedding)
        }
      }
    }
